on: push
name: Ejecutar test y hacer deploy a heroku
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar y moverse a la rama actual
        uses: actions/checkout@v1
      - name: Instalar depencias de node
        run: npm install
      - name: Ejecutar tests
        run: npm test
      - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:master -f
